### PR TITLE
Replace Glue dependency. Fixes #6

### LINKED ISSUE #6: Remove unmaintained Glue dependency
Unfortunately, the [Glue](https://github.com/jorgebastida/glue) dependency has not seen an update in over three years, with many issues outstanding and unaddressed. Most importantly, Glue has [pinned Jinja2](https://github.com/jorgebastida/glue/blob/master/setup.py#L7) to a narrow set of acceptable versions (`Jinja2>=2.7,<2.10`), making it impossible to install Glue alongside the current version of Pelican, since Pelican currently requires `Jinja2 >= 2.11`.

One potential solution would be to loosen the restriction on Pelican’s side, accepting `Jinja2 >= 2.09`. That *might* work, but it would only be a temporary bandaid, since the next Jinja2 update containing significant changes would bring us right back to the same problem.

Other solutions include:

* find an alternative project to provide the functionality that Glue currently provides

* convince @jorgebastida to release a new version of Glue with updated Jinja2 requirements, preferably by specifying only a minimum version and eliminating the maximum version constraint

* fork Glue, fix it, and re-publish to PyPI under a different name

@Ceralor / @jorgebastida: What do you think?

### PR DESCRIPTION
**Pull request by KayOhtie**
Removed Glue as a dependency by reimplementing the functionality modeled off of https://github.com/ionelmc/python-css-sprite

Also changed replacement markup to remove the span with invisible text in favor of `aria-label` for accessibility.

### CODE REVIEW

**Comment by KayOhtie** [comment]
Would like to potentially update other build deps, but I also imagine it can be changed heavily overall. Are all of those dev deps required?

**Comment by justinmayer** [comment]
Yay! I'm really happy to see a path forward for this plugin that does not involve the Glue dependency. Thank you for making this happen! 🌟 

Regarding your question, I would also like to simplify the development tooling dependencies. I've already done 80% of that work for another plugin, and I'd be happy to do the other 20% as part of re-tooling this plugin's development flow.

To that end, what I'd like to do with this PR is:

* Squash the pre-commit.ci auto-fixes (https://github.com/pelican-plugins/pelimoji/pull/8/commits/c5d02292a168263885e203c5c315fd74d3423f64) into the [Reimplemented Glue functionality](https://github.com/pelican-plugins/pelimoji/pull/8/commits/e77311b7f467893cb86dfc0258067cfaf80c533e) parent commit.
* Drop the two commits related to updating Python dependency to 3.7 or above (I'll do this a bit differently in a separate PR).

So in the end, the four commits related to replacing Glue would remain. Then we can merge this PR and move on to the development tooling topic. How does that sound to you?

**Comment by KayOhtie** [comment]
Sounds good! I may need a top on doing the squash, I've never done that
before with Git, but sounds good overall! I do want to see if there's a
better signal to hook into for steps, or if I should be adding the
match/replace stuff to the global context, but that can be the next
improvement step.

**Comment by justinmayer** [comment]
There were some spurious commits in the PR, so I cleaned them up into the original four target commits. I'm going to merge this now, and we can continue the development in follow-up commits/PRs.

Once again, bravo on this big step forward! 💫

**Pull request merged**
