### PR TITLE
Move to new namespace plugin filesystem layout

### PR DESCRIPTION
**Pull request by justinmayer**
I found a few minutes to adjust Pelimoji to the new namespace plugin format. Aside from moving some files around, no changes were required except for adjusting the path to the `pelimoji/css.j2` file. 🚀

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Kay! 👋  I tested Pelimoji in this new namespace plugin form, and it works great. Would you mind having a look at this pull request and letting me know what you think?

Thanks again for making this plugin. I'm looking forward to using it with a few of my Pelican-powered projects! 😁

**Comment by KayOhtie** [comment]
Thank you for taking a look and cleaning it up! I'm so glad to hear it worked well! And thank you for the variable substitution for the plugin path. I should have thought to do that before, even if it'd require a change now.

Out of curiosity are the split imports to meet a standard for these or just a preference?

**Comment by justinmayer** [comment]
Putting unrelated imports on separate lines is a [Python PEP-8 convention](https://www.python.org/dev/peps/pep-0008/#imports). I should have perhaps made that change in the context of a separate commit, but since I was already making some changes to the `os.path` imports, it seems I absentmindedly made those PEP-8 changes at the same time. I'm happy to separate those code-style changes out in a separate commit if you prefer. 😊

**Comment by KayOhtie** [comment]
That makes sense, I wasn't entirely aware but suspected it was PEP-8! Thank you for the modifications!

**Pull request merged**
